services:
  notenschluessel:
    image: payback159/notenschluessel:latest
    ports:
      - "8080:8080"
    volumes:
      - /tmp:/tmp
    restart: unless-stopped
    # Security options
    security_opt:
      - no-new-privileges:true
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M